import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  TOOL_DEFINITION,
  TOOL_NAME,
  createMcpServer,
  handleMaybeExecuteLocally,
} from "../src/mcp/server.js";
import { invalidateRulesCache } from "../src/rules/loader.js";

/**
 * The MCP tool handler is the surface every AI client actually calls, and it
 * receives arguments generated by an LLM — so the interesting cases are the
 * malformed ones. These drive the real server over an in-memory transport
 * (same code path as stdio, no subprocess) plus the handler directly.
 */

let home: string;
let origEnv: NodeJS.ProcessEnv;

beforeEach(async () => {
  origEnv = { ...process.env };
  home = await mkdtemp(join(tmpdir(), "ninja-mcp-"));
  process.env.XDG_CONFIG_HOME = join(home, "config");
  await mkdir(process.env.XDG_CONFIG_HOME, { recursive: true });
  invalidateRulesCache();
});

afterEach(async () => {
  process.env = origEnv;
  invalidateRulesCache();
  await rm(home, { recursive: true, force: true });
});

async function connectedClient(): Promise<Client> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const server = createMcpServer();
  const client = new Client({ name: "test", version: "0" }, { capabilities: {} });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  return client;
}

function payload(result: unknown): Record<string, unknown> {
  const content = (result as { content: Array<{ type: string; text: string }> }).content;
  expect(content[0]!.type).toBe("text");
  return JSON.parse(content[0]!.text) as Record<string, unknown>;
}

describe("mcp server — tool listing", () => {
  it("advertises exactly the maybe_execute_locally tool", async () => {
    const client = await connectedClient();
    const { tools } = await client.listTools();
    expect(tools).toHaveLength(1);
    expect(tools[0]!.name).toBe(TOOL_NAME);
    await client.close();
  });

  it("declares command as the only required input", () => {
    expect(TOOL_DEFINITION.inputSchema.required).toEqual(["command"]);
    expect(TOOL_DEFINITION.inputSchema.properties.command.type).toBe("string");
  });
});

describe("mcp server — callTool", () => {
  it("executes a matched command and returns structured output", async () => {
    const client = await connectedClient();
    const result = await client.callTool({
      name: TOOL_NAME,
      arguments: { command: "pwd", context: { cwd: home } },
    });
    const body = payload(result);
    expect(body.handled).toBe(true);
    expect(body.exit_code).toBe(0);
    expect(String(body.stdout)).toContain(home.split("/").pop()!);
    expect(typeof body.rule_id).toBe("string");
    await client.close();
  });

  it("reports no_match instead of guessing", async () => {
    const client = await connectedClient();
    const result = await client.callTool({
      name: TOOL_NAME,
      arguments: { command: "zzzq please refactor the auth module for me" },
    });
    expect(payload(result).handled).toBe(false);
    expect(payload(result).reason).toBe("no_match");
    await client.close();
  });

  it("refuses a command the safety validator blocks", async () => {
    const client = await connectedClient();
    const result = await client.callTool({
      name: TOOL_NAME,
      arguments: { command: "rm -rf /" },
    });
    const body = payload(result);
    expect(body.handled).toBe(false);
    expect(body.reason).toBe("safety_block");
    await client.close();
  });

  it("returns an error payload for an unknown tool name", async () => {
    const client = await connectedClient();
    const result = await client.callTool({ name: "not_a_tool", arguments: {} });
    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(payload(result).reason).toBe("unknown_tool");
    await client.close();
  });
});

describe("handleMaybeExecuteLocally — untrusted arguments", () => {
  it("treats a missing command as empty rather than throwing", async () => {
    expect(await handleMaybeExecuteLocally(undefined)).toEqual({
      handled: false,
      reason: "empty_command",
    });
  });

  it("coerces a non-string command to empty", async () => {
    expect(await handleMaybeExecuteLocally({ command: 42 })).toEqual({
      handled: false,
      reason: "empty_command",
    });
    expect(await handleMaybeExecuteLocally({ command: { nested: true } })).toEqual({
      handled: false,
      reason: "empty_command",
    });
  });

  it("ignores a non-string cwd instead of passing it to execa", async () => {
    const result = await handleMaybeExecuteLocally({
      command: "pwd",
      context: { cwd: 123 },
    });
    expect(result.handled).toBe(true);
  });
});
